### ISSUE TITLE
Calender tab shows language other than English

### ISSUE THREAD

**Issue by sakibarifin** [dit-calendar/dit-calendar-bot#11]
![image](https://user-images.githubusercontent.com/33556544/127138604-58a6fae2-c00d-4d12-9738-f4edd98baee5.png)

Many people won't understand what it means as it is not in English.

**Comment by vitaB** [comment]
you have to use another calender ([caldav](https://github.com/dit-calendar/caldav-telegram-bot) or [teamup](https://github.com/dit-calendar/teamup-telegram-bot)) for the moment. This one no longer works because we need another infra provider for the server.

**Comment by vitaB** [comment]
duplicate https://github.com/dit-calendar/dit-calendar-bot/issues/10
